# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
solc = "0.8.19"
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./out" },
]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 0 # TODO: add 
extra_output = ["devdoc"]

[rpc_endpoints]
local = "http://0.0.0.0:8545"
arbitrum = "http://0.0.0.0:8545"
stage = "https://rpc.ankr.com/polygon_mumbai"
testnet = "https://rpc.ankr.com/polygon_mumbai"
kras = "https://rpc.ankr.com/polygon_mumbai"
mumbai = "https://rpc.ankr.com/polygon_mumbai"
