# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
test = "src"
script = "src"
libs = ["lib"]

solc = "0.8.24"
evm_version = "london"
via_ir = true
optimizer = true
optimizer_runs = 0

fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./out" },
]
gas_reports = ["*"]
extra_output = ["devdoc"]

[rpc_endpoints]
local = "http://0.0.0.0:8545"
arbutrum = "http://0.0.0.0:8545"
stage = "https://ipc-stage.fluence.dev"
dar = "https://ipc.dar.fluence.dev"
kras = "https://ipc.kras.fluence.dev"
mumbai = "https://rpc.ankr.com/polygon_mumbai"

[profile.test]
src = "test"
out = "test-out"
test = "test"
script = "test"
via_ir = false
optimizer = false
