# This docker-compose is used for DEV purposes. It is also used in CI
# to generate deployments/local.json file.
#
# It consists of chain-deploy-script container with volume mounting to the host:
#  - thus, your deployments/<>.json might be changed after contract redeployed;
#  - also, cache/ and out/ with contract artifacts is mounted to the host as well.
#
# To use from ../: `docker compose -f ./docker/docker-compose.yml up`.
#
# Note, if you changed contracts and what to use docker-compose instead of local make command to deploy
#  - you should rebuild with --build flag.
#
# Note, deploy may take some time, check logs.
#
volumes:
  postgres:
  ipfs:
  cometbft:
  ipc:

services:
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - "5001:5001"
    volumes:
      - ipfs:/data/ipfs

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres:/var/lib/postgresql/data

  # IPC
  ipc:
    image: ${IPC_IMAGE:-ipc}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: ipc
    environment:
      FM_NETWORK: testnet
      TENDERMINT_RPC_URL: http://cometbft:26657
    ports:
      - "26658:26658"
    volumes:
      - ipc:/fendermint/data

  # Blockchain backend
  cometbft:
    image: ${COMETBFT_IMAGE:-cometbft}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: cometbft
    environment:
      CMT_LOG_LEVEL: "main:info,abci-client:debug,*:error"
      CMT_LOG_FORMAT: "plain"
      CMT_PROXY_APP: "tcp://ipc:26658"
    ports:
      - "26657:26657"
    volumes:
      - cometbft:/cometbft/data
    healthcheck:
      test: curl --fail http://localhost:26657 || exit 1
      interval: 8s
      timeout: 10s
      retries: 20
    depends_on:
      - ipc

  ipc-eth:
    image: ${IPC_IMAGE:-ipc}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: ipc
    environment:
      FM_NETWORK: testnet
      TENDERMINT_RPC_URL: "http://cometbft:26657"
      TENDERMINT_WS_URL: "ws://cometbft:26657/websocket"
    command: "eth run"
    ports:
      - "8545:8545"
    healthcheck:
      test: |
        curl -s -X POST 'http://localhost:8545' -H 'Content-Type: application/json' \
          --data '{"jsonrpc":"2.0", "method":"eth_chainId", "params":[], "id":1}' \
          | jq -e '.result != null'
      interval: 8s
      timeout: 10s
      retries: 20
    depends_on:
      cometbft:
        condition: service_healthy

  ipc-deploy-script:
    image: ${IPC_DEPLOY_SCRIPT_IMAGE:-ipc-deploy-script}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: ipc-deploy-script
    command: ["deploy-to-ipc"]
    volumes:
      - ../deployments/:/app/deployments/
      - ../out/:/app/out/
      - ../cache/:/app/cache/
    depends_on:
      ipc-eth:
        condition: service_healthy

  # Blockscout services
  blockscout:
    depends_on:
      - ipc-eth
      - postgres
    image: offchainlabs/blockscout:v1.0.0-c8db5b1
    restart: always
    links:
      - postgres:database
    command:
      - /bin/sh
      - -c
      - |
        bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()"
        node init/install.js postgres 5432
        bin/blockscout start
    environment:
      ETHEREUM_JSONRPC_VARIANT: "geth"
      ETHEREUM_JSONRPC_HTTP_URL: http://ipc-eth:8545/
      ETHEREUM_JSONRPC_TRACE_URL: http://ipc-eth:8545/
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
      DATABASE_URL: postgresql://postgres:@postgres:5432/blockscout
      ECTO_USE_SSL: "false"
      NETWORK: ""
      SUBNETWORK: "Fluence Local Network"
      BLOCKSCOUT_VERSION: "Fluence Local Network 0.0.1"
      PORT: 4000
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      ipc-eth:
        condition: service_healthy

  graph-node:
    image: graphprotocol/graph-node:v0.33.0
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
      - ipc-eth
    environment:
      postgres_host: postgres
      postgres_user: postgres
      postgres_pass: ""
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      ethereum: 'local:http://ipc-eth:8545'
      GRAPH_LOG: info
      # https://github.com/graphprotocol/graph-node/issues/3159#issuecomment-1062827725
      ETHEREUM_REORG_THRESHOLD: 1
      ETHEREUM_ANCESTOR_COUNT: 1
    depends_on:
      ipc-eth:
        condition: service_healthy
