services:
  # Anvil node with deployed contracts
  anvil-node:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.anvil
    ports:
      - "8545:8545"

  deploy-script:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.deploy
    depends_on:
      - anvil-node

  # Blockscout services
  blockscout:
    depends_on:
      - anvil-node
    image: blockscout/blockscout:latest
    restart: always
    links:
      - postgres:database
    command:
      - /bin/sh
      - -c
      - |
        bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()"
        node init/install.js postgres 5432
        bin/blockscout start
    environment:
      ETHEREUM_JSONRPC_VARIANT: "geth"
      ETHEREUM_JSONRPC_HTTP_URL: http://anvil-node:8545/
      ETHEREUM_JSONRPC_TRACE_URL: http://anvil-node:8545/
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
      DATABASE_URL: postgresql://postgres:@postgres:5432/blockscout
      ECTO_USE_SSL: "false"
      NETWORK: ""
      SUBNETWORK: "Fluence Local Network"
      BLOCKSCOUT_VERSION: "Fluence Local Network 0.0.1"
      PORT: 4000
    ports:
      - "127.0.0.1:4000:4000"

  postgres:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
