sources:
  - name: CoreImpl
    handler:
      graphql:
        endpoint: http://localhost:8000/subgraphs/name/fluence-deal-contracts
    transforms:
      - autoPagination:
          # Validates that the schema source actually contains the required input filters.
          validateSchema: true
          # Default is 1000, you can change if your indexer has different configuration in GRAPH_GRAPHQL_MAX_FIRST var.
          limitOfRecords: 100


documents:
  - ./src/indexerClient/offers-query.graphql
  - ./src/indexerClient/providers-query.graphql
  - ./src/indexerClient/deals-query.graphql
