name: "ci"

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - run: npm install --f
      - run: npm run build
        env:
          PRIVATE_KEY: ${{ secrets.DEAL_TESNET_PRIVATE_KEY }}
