name: "ci"

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and run
        uses: isbang/compose-action@v1.4.1

      - name: Ping
        run: curl localhost:8545 --data '{"jsonrpc": "2.0", "id": 1, "method": "eth_accounts"}' | jq
