name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/artifacts.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/artifacts.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  deal:
    if: >
      github.event_name == 'push' ||
      (
        contains(github.event.pull_request.labels.*.name, 'e2e') &&
        !github.event.pull_request.head.repo.fork
      )
    uses: ./.github/workflows/artifacts.yml
    with:
      ref: ${{ github.ref }}
    secrets:
      token: ${{ secrets.FLUENCEBOT_RELEASE_PLEASE_PAT }}

  # cli:
  #   needs:
  #     - deal
  #   # TODO: change on main below when https://github.com/fluencelabs/cli/pull/654 is merged.
  #   uses: fluencelabs/cli/.github/workflows/tests.yml@capacity
  #   with:
  #     ref: main
  #     ipc-image: "${{ needs.deal.outputs.ipc-image }}"
  #     ipc-deploy-script-image: "${{ needs.deal.outputs.ipc-deploy-script-image }}"
  #     cometbft-image: "${{ needs.deal.outputs.cometbft-image }}"
  #     subgraph-deploy-script-image: "${{ needs.deal.outputs.subgraph-deploy-script-image }}"
  #     deal-ts-clients-version: "${{ needs.deal.outputs.deal-ts-clients-version }}"
