name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/artifacts.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  deal:
    if: >
      github.event_name == 'push' ||
      (
        contains(github.event.pull_request.labels.*.name, 'e2e') &&
        !github.event.pull_request.head.repo.fork
      )
    uses: ./.github/workflows/artifacts.yml
    with:
      ref: ${{ github.ref }}
    secrets:
      token: ${{ secrets.FLUENCEBOT_RELEASE_PLEASE_PAT }}

  cli:
    needs:
      - deal
    uses: fluencelabs/cli/.github/workflows/tests.yml@main
    with:
      chain-rpc-image: "${{ needs.deal.outputs.chain-rpc-image }}"
      chain-deploy-script-image: "${{ needs.deal.outputs.chain-deploy-script-image }}"
      subgraph-deploy-script-image: "${{ needs.deal.outputs.subgraph-deploy-script-image }}"
      deal-ts-clients-version: "${{ needs.deal.outputs.deal-ts-clients-version }}"
