name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  deal:
    if: >
      github.event_name == 'push' ||
      (
        contains(github.event.pull_request.labels.*.name, 'e2e') &&
        !github.event.pull_request.head.repo.fork
      )
    uses: ./.github/workflows/snapshot.yml
    with:
      ref: ${{ github.ref }}

  # cli:
  #   needs:
  #     - deal
  #   uses: fluencelabs/cli/.github/workflows/tests.yml@main
  #   with:
  #     deal-aurora-image: "${{ needs.deal.outputs.image }}"
  #     deal-aurora-version: "${{ needs.deal.outputs.version }}"
