name: lint

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lints:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Renovate Config Validator
        uses: tj-actions/renovate-config-validator@v2
        with:
          config_file: .github/renovate.json
