name: Publish snapshots

on:
  workflow_call:
    inputs:
      ref:
        description: "GitHub ref to checkout to"
        type: string
        default: "master"
    outputs:
      deal-ts-clients-version:
        description: "@fluencelabs/deal-ts-clients version"
        value: ${{ jobs.npm.outputs.deal-ts-clients-version }}
      subgraph-version:
        description: "@fluencelabs/subgraph version"
        value: ${{ jobs.npm.outputs.subgraph-version }}
      deal-deploy-script-image:
        description: "deal deploy script container image"
        value: ${{ jobs.containers.outputs.deal-deploy-script-image }}
      chain-rpc-image:
        description: "chain RPC container image"
        value: ${{ jobs.containers.outputs.chain-rpc-image }}

env:
  FORCE_COLOR: true

jobs:
  containers:
    name: "Publish ${{ matrix.arch }} containers"

    strategy:
      matrix:
        include:
          - arch: amd64
            runner: linux-amd64-m-xlarge
          - arch: arm64
            runner: linux-arm64-m-xlarge

    runs-on: ${{ matrix.runner }}

    outputs:
      chain-rpc-image: "docker.fluence.dev/chain-rpc@${{ steps.version.outputs.versions.id }}"
      deal-deploy-script-image: "docker.fluence.dev/deal-deploy-script@${{ steps.version.outputs.id }}"

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fluencelabs/deal
          ref: ${{ inputs.ref }}

      - name: Import secrets
        uses: hashicorp/vault-action@v2.7.3
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/hub.docker.com/fluencebot username | DOCKER_HUB_USERNAME ;
            kv/hub.docker.com/fluencebot password | DOCKER_HUB_PASSWORD ;
            kv/docker-registry/basicauth/ci username | DOCKER_USERNAME ;
            kv/docker-registry/basicauth/ci password | DOCKER_PASSWORD

      - name: Generate snapshot version
        id: version
        uses: fluencelabs/github-actions/generate-snapshot-id@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Login to private docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.fluence.dev
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build contracts
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: docker/Dockerfile
          target: contracts
          platforms: linux/${{ matrix.arch }}

      - name: Build and push chain-rpc image
        id: chain-rpc
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          provenance: false
          dockerfile: docker/Dockerfile
          target: chain-rpc
          platforms: linux/${{ matrix.arch }}
          tags: |
            docker.fluence.dev/chain-rpc:${{ steps.version.outputs.id }}-${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push deal-deploy-script image
        id: deal-deploy-script
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          provenance: false
          dockerfile: docker/Dockerfile
          target: chain-rpc
          platforms: linux/${{ matrix.arch }}
          tags: |
            docker.fluence.dev/deal-deploy-script:${{ steps.version.outputs.id }}-${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  manifest:
    name: "Merge arch images"
    needs: containers

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Import secrets
        uses: hashicorp/vault-action@v2.7.3
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/docker-registry/basicauth/ci username | DOCKER_USERNAME ;
            kv/docker-registry/basicauth/ci password | DOCKER_PASSWORD

      - name: Login to private docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.fluence.dev
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Merge chain-rpc containers
        uses: Noelware/docker-manifest-action@0.4.0
        with:
          inputs: docker.fluence.dev/chain-rpc:${{ needs.containers.outputs.version }}
          images: docker.fluence.dev/chain-rpc:${{ needs.containers.outputs.version }}-amd64,docker.fluence.dev/chain-rpc:${{ needs.container.outputs.version }}-arm64
          push: true
          amend: true

      - name: Merge deal-deploy-script containers
        uses: Noelware/docker-manifest-action@0.4.0
        with:
          inputs: docker.fluence.dev/deal-deploy-script:${{ needs.containers.outputs.version }}
          images: docker.fluence.dev/deal-deploy-script:${{ needs.containers.outputs.version }}-amd64,docker.fluence.dev/deal-deploy-script:${{ needs.container.outputs.version }}-arm64
          push: true
          amend: true

  deploy:
    name: "Generate deployments/local.json"
    needs:
      - manifest
      - containers

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fluencelabs/deal
          ref: ${{ inputs.ref }}

      - name: Import secrets
        uses: hashicorp/vault-action@v2.7.3
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/docker-registry/basicauth/ci username | DOCKER_USERNAME ;
            kv/docker-registry/basicauth/ci password | DOCKER_PASSWORD

      - name: Setup docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1

      - name: Run deployment script
        env:
          CHAIN_RPC_IMAGE: docker.fluence.dev/chain-rpc:${{ needs.containers.outputs.version }}
          DEAL_DEPLOY_SCRIPT_IMAGE: docker.fluence.dev/deal-deploy-script:${{ needs.containers.outputs.version }}
        working-directory: docker
        run: docker-compose up deal-deploy-script

      - name: Upload deployments/local.json
        uses: actions/upload-artifact@v4
        with:
          name: local.json
          path: deployments/local.json

  npm:
    name: "Publish npm snapshots"
    runs-on: linux-amd64-m-xlarge
    timeout-minutes: 60

    needs: deploy

    outputs:
      deal-ts-clients: "${{ steps.deal-ts-clients.outputs.version }}"
      subgraph: "${{ steps.subgraph.outputs.version }}"

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fluencelabs/deal
          ref: ${{ inputs.ref }}

      - name: Import secrets
        uses: hashicorp/vault-action@v2.7.3
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/npm-registry/basicauth/ci token | NODE_AUTH_TOKEN

      - name: Setup node with self-hosted npm registry
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.fluence.dev"
          cache: "npm"
          cache-dependency-path: |
            ts-client/package-lock.json
            subgraph/package-lock.json

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Download deployments/local.json
        uses: actions/download-artifact@v4
        with:
          name: local.json
          path: deployments/

      - name: Build contracts
        run: make build-contracts

      - name: Build contracts and npm packages
        run: make install-npms

      - name: Build npm packages
        run: make build-npms

      - name: Generate snapshot version
        id: version
        uses: fluencelabs/github-actions/generate-snapshot-id@main

      - name: Publish deal-ts-clients snapshot
        id: deal-ts-clients
        uses: fluencelabs/github-actions/npm-publish-snapshot@main
        with:
          id: ${{ steps.version.outputs.id }}
          working-directory: ts-client/

      - name: Publish subgraph snapshot
        id: subgraph
        uses: fluencelabs/github-actions/npm-publish-snapshot@main
        with:
          id: ${{ steps.version.outputs.id }}
          working-directory: subgraph/
