name: "test"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/test.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/test.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

env:
  FORCE_COLOR: true
  FOUNDRY_PROFILE: "ci"

jobs:
  build:
    name: "Build contracts and npm packages"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: |
            ts-client/package-lock.json
            subgraph/package-lock.json

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: make install-npms
      - run: make build-all

  foundry:
    name: "Foundry unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes

      - name: Run Forge tests
        run: forge test -vvv

  integration-tests:
    name: "Integration tests"
    runs-on: ubuntu-latest
    steps:
      - name: Run docker network
        run: docker compose up -d
        working-directory: .github

      - name: Install deps in ts-client package
        run: npm run i
        working-directory: ts-client

      - name: Build ts-client package
        run: npm run build
        working-directory: ts-client

      - name: Pack ts-client package
        id: pack-ts-client
        run: echo "TS_CLIENT_ARCHIVE=$(npm pack --silent --pack-destination ../integration-tests)\n" >> $GITHUB_OUTPUT
        working-directory: ts-client

      - name: Install packed ts-client
        run: npm i ${{ steps.pack-ts-client.outputs.TS_CLIENT_ARCHIVE }}
        working-directory: integration-tests

      - name: Run integration tests
        run: npm run test deal.test
        working-directory: integration-tests