name: "test"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/test.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/test.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

env:
  FORCE_COLOR: true
  FOUNDRY_PROFILE: "ci"

jobs:
  build:
    name: "Build contracts and npm packages"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: |
            ts-client/package-lock.json
            subgraph/package-lock.json

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: make install-npms
      - run: make build-all

  foundry:
    name: "Foundry unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes

      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3

      - name: Run Forge tests
        run: forge test -vvv
